name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Client
        run: sudo apt-get update && sudo apt-get install -y openssh-client
      - name: connect to ec2 instance
        run: ssh -i "local-ssh.pem" ec2-user@ec2-3-86-179-237.compute-1.amazonaws.com
