name: Deploy to EC2

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SSH Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}  # EC2 instance public IP or hostname
          username: ${{ secrets.EC2_USERNAME }}  # SSH username
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH private key
          script: |
            cd /home/ec2_user/git_pulled_data
            git pull origin main  # Pull changes from GitHub

