name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SSH Client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Connect to EC2 and Pull Latest Code
        uses: garygrossgarten/github-action-ssh@v0.1.7
        with:
          command: |
            cd /home/ec2_user/git_pulled_data
            git pull origin main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_KEY }}
          SSH_HOST: ${{ secrets.EC2_HOST }}
          SSH_USER: ${{ secrets.EC2_USER }}
